### ISSUE TITLE
[Feat] Add a button to repeat attack/damage

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#265] opened 2023-07-24 02:42 UTC
Add a button to chat cards to repeat the attack/damage roll to a new chat card. This is useful for spells like scorching ray and magic missiles.

**Comment by Pjb518** [comment] 2023-10-05 09:18
This is a duplicate of #76.

**Closed by Pjb518** 2023-10-05 09:18 UTC
Labels: type: new feature
